// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnB0kV67t4TZ7zjktnDO57sBPHs-w847w',
    appId: '1:950587682922:web:83bc33ee83be6fd279da13',
    messagingSenderId: '950587682922',
    projectId: 'chaja-kiganjani',
    authDomain: 'chaja-kiganjani.firebaseapp.com',
    storageBucket: 'chaja-kiganjani.firebasestorage.app',
    measurementId: 'G-FNB7Z5MVLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVa9zjuRegFeg0TL9ajGoRo4F_-U9dJI',
    appId: '1:950587682922:android:9811fd9c89cd608479da13',
    messagingSenderId: '950587682922',
    projectId: 'chaja-kiganjani',
    storageBucket: 'chaja-kiganjani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIq6rVgad_ta45tSGh-L4cQE0DfbXwO7A',
    appId: '1:950587682922:ios:acf36eebc9e0d8de79da13',
    messagingSenderId: '950587682922',
    projectId: 'chaja-kiganjani',
    storageBucket: 'chaja-kiganjani.firebasestorage.app',
    iosBundleId: 'com.example.smartChaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIq6rVgad_ta45tSGh-L4cQE0DfbXwO7A',
    appId: '1:950587682922:ios:acf36eebc9e0d8de79da13',
    messagingSenderId: '950587682922',
    projectId: 'chaja-kiganjani',
    storageBucket: 'chaja-kiganjani.firebasestorage.app',
    iosBundleId: 'com.example.smartChaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnB0kV67t4TZ7zjktnDO57sBPHs-w847w',
    appId: '1:950587682922:web:593b28b612a51d8279da13',
    messagingSenderId: '950587682922',
    projectId: 'chaja-kiganjani',
    authDomain: 'chaja-kiganjani.firebaseapp.com',
    storageBucket: 'chaja-kiganjani.firebasestorage.app',
    measurementId: 'G-BCN9N0P64Y',
  );
}
